apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: template-plugin-azurepipelines
  title: Azure Pipelines
  description: Template for use Azure Devops Pipelines
spec:
  owner: alanFMA
  type: website
  parameters:
    - title: Kode3Tech
      required:
        - selectazurepipelines
      properties:
        org:
          title: Organization
          type: string
          description: Choose an Azure DevOps Organization
          ui:field: AzureOrganizationPicker
        owner:
          title: Project
          type: string
          description: Choose an Azure DevOps Project
          ui:field: AzureProjectPicker
          ui:options:
            organizationRef: org
        selectazurepipelines:
          title: Azure Pipelines
          type: array
          items:
            type: string
          description: É obrigatório a seleção de pelo menos uma pipeline.
          ui:field: SelectAzurePipelines
    - title: Confirmação
      properties:
        confirmationmessage:
          title: Confirmação
          type: boolean
          description: Deseja realmente prosseguir com esta ação?
          ui:field: ConfirmationMessage

  # here's the steps that are executed in series in the scaffolder backend
  steps:
    - id: kode3:remove-azure-pipelines
      name: Kode3 Remove Azure Pipelines
      action: kode3:remove-azure-pipelines
      input:
        context: ${{ parameters.context }}
        selectazurepipelines: ${{ parameters.selectazurepipelines }}
        organization: ${{parameters.org}}
        project: ${{parameters.owner}}
  review:
    omitSteps:
      - Confirmação
    # - id: fetch-docs
    #   name: Fetch Docs
    #   action: fetch:plain
    #   input:
    #     targetPath: ./community
    #     url: https://github.com/backstage/community/tree/main/backstage-community-sessions

    # - id: publish
    #   name: Publish
    #   action: publish:github
    #   input:
    #     allowedHosts: ['github.com']
    #     description: This is ${{ parameters.name }}
    #     repoUrl: ${{ parameters.repoUrl }}
