apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: react-ssr-template
  title: React SSR Template
  description: Create a website powered with Next.js
  tags:
    - recommended
    - react
spec:
  owner: alanFMA
  type: website
  parameters:
    - title: Provide some simple information
      required:
        - component_id
        - owner
        - url
        - programming
        - multiselect
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
        url:
          title: URL
          type: string
          description: Digite a url do Nestjs
          ui:field: ValidateKebabCase
        programming:
          title: Programming
          type: string
          description: Escolha uma linguagem
          ui:field: Programming
        multiselect:
          title: MultiSelect
          type: array
          items:
            type: string
          description: Selecione a(s) linguagem(ns)
          ui:field: MultiSelect
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender:
          - .github/workflows/*
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          owner: ${{ parameters.owner }}

    # - id: publish
    #   name: Publish
    #   action: publish:github
    #   input:
    #     allowedHosts: ['github.com']
    #     description: This is ${{ parameters.component_id }}
    #     repoUrl: ${{ parameters.repoUrl }}

    # - id: register
    #   name: Register
    #   action: catalog:register
    #   input:
    #     repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
    #     catalogInfoPath: '/catalog-info.yaml'

    - id: kode3:plugin-middlewares
      name: Kode3 Get Group config
      action: kode3:plugin-middlewares
      input:
        component_id: ${{ parameters.component_id }}
        owner: ${{ parameters.owner }}
        url: ${{ parameters.url }}
        programming: ${{ parameters.programming }}
        multiselect: ${{ parameters.multiselect }}

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
